services:
  acapy-control:
    environment:
      REFERENCE_AGENT_NGROK_DOMAIN: ${REFERENCE_AGENT_NGROK_DOMAIN:-${ISSUER_NGROK_DOMAIN:-}}
      ISSUER_NGROK_DOMAIN: ${ISSUER_NGROK_DOMAIN:-${REFERENCE_AGENT_NGROK_DOMAIN:-}}
      #ACAPY_LOG_LEVEL: debug   # or trace, info, etc.
      #ACAPY_TRACE: "true"      # optional, for full DIDComm traces
  acapy-ngrok:
    environment:
      REFERENCE_AGENT_NGROK_DOMAIN: ${REFERENCE_AGENT_NGROK_DOMAIN:-${ISSUER_NGROK_DOMAIN:-}}
      ISSUER_NGROK_DOMAIN: ${ISSUER_NGROK_DOMAIN:-${REFERENCE_AGENT_NGROK_DOMAIN:-}}
